/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dashboard;

/**
 *
 * @author HP
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
         initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dashboard = new javax.swing.JPanel();
        petrecords_btn = new javax.swing.JButton();
        petgallery_btn = new javax.swing.JButton();
        appointment_btn = new javax.swing.JButton();
        medications_btn = new javax.swing.JButton();
        contacts_btn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dashboard.setBackground(new java.awt.Color(153, 153, 153));
        dashboard.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        dashboard.setMinimumSize(new java.awt.Dimension(0, 0));
        dashboard.setPreferredSize(new java.awt.Dimension(800, 500));
        dashboard.setLayout(new java.awt.GridBagLayout());

        petrecords_btn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        petrecords_btn.setText("PET RECORDS");
        petrecords_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petrecords_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 129;
        gridBagConstraints.ipady = 58;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 153, 0, 0);
        dashboard.add(petrecords_btn, gridBagConstraints);

        petgallery_btn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        petgallery_btn.setText("PET GALLERY");
        petgallery_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petgallery_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 132;
        gridBagConstraints.ipady = 58;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 154, 0, 0);
        dashboard.add(petgallery_btn, gridBagConstraints);

        appointment_btn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        appointment_btn.setText("APPOINTMENT SCHEDULING");
        appointment_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointment_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 51;
        gridBagConstraints.ipady = 58;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 30, 0, 0);
        dashboard.add(appointment_btn, gridBagConstraints);

        medications_btn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        medications_btn.setText("MEDICATIONS / HEALTH TRACKING");
        medications_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medications_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 285;
        gridBagConstraints.ipady = 58;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 154, 101, 0);
        dashboard.add(medications_btn, gridBagConstraints);

        contacts_btn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        contacts_btn.setText("EMERGENCY CONTACTS & VET INFO");
        contacts_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contacts_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 58;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 30, 0, 0);
        dashboard.add(contacts_btn, gridBagConstraints);

        logout_btn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        logout_btn.setText("LOGOUT");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 25);
        dashboard.add(logout_btn, gridBagConstraints);

        getContentPane().add(dashboard, java.awt.BorderLayout.CENTER);
        dashboard.getAccessibleContext().setAccessibleName("dashboard");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void petrecords_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petrecords_btnActionPerformed
    PetRecords pr = new PetRecords();
    pr.setVisible(true);
    this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_petrecords_btnActionPerformed

    private void petgallery_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petgallery_btnActionPerformed
    PetPhotos ap = new PetPhotos ();
    ap.setVisible(true);
    this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_petgallery_btnActionPerformed

    private void appointment_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointment_btnActionPerformed
    AppointmentSched ap = new AppointmentSched();
    ap.setVisible(true);
    this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_appointment_btnActionPerformed

    private void medications_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medications_btnActionPerformed
    Medications med = new Medications();
    med.setVisible(true);
    this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_medications_btnActionPerformed

    private void contacts_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contacts_btnActionPerformed
    Contacts c = new Contacts();
    c.setVisible(true);
    this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_contacts_btnActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
         int choice = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Logout",
            javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (choice == javax.swing.JOptionPane.YES_OPTION) {
        // Open LoginForm again
        new Authentication.LoginForm().setVisible(true);

        // Close the Dashboard
        this.dispose();
    }
// TODO add your handling code here:
    }//GEN-LAST:event_logout_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appointment_btn;
    private javax.swing.JButton contacts_btn;
    private javax.swing.JPanel dashboard;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton medications_btn;
    private javax.swing.JButton petgallery_btn;
    private javax.swing.JButton petrecords_btn;
    // End of variables declaration//GEN-END:variables
}
